version: '3.8'

services:

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090/tcp
    volumes:
      - ${PWD}/volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/volumes/prometheus/rules.yml:/etc/prometheus/rules.yml
      - ${PWD}/volumes/prometheus/alertmanager.yml:/etc/prometheus/alertmanager.yml

  node_exporter:
    image: quay.io/prometheus/node-exporter
    ports:
      - "9100:9100"

  alertmanager:
    image: quay.io/prometheus/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ${PWD}/volumes/prometheus/alertmanager.yml:/etc/prometheus/alertmanager.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/volumes/grafana/:/var/lib/grafana/

  yace:
    image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.30.1-alpha
    volumes:
      - ${PWD}/volumes/yace/config.yml:/tmp/config.yml
    command: ["--config.file=/tmp/config.yml", "--scraping-interval=60", "--decoupled-scraping=true", "--debug=true"]
    env_file: .env
    ports:
      - "5000:5000"

      
